site_name: Configurações
site_description: Instruções de configuração de de sistemas, serviços, aplicações, etc.
site_author: Getúlio Vinicius <getuliovinits@gmail.com
google_analytics: ['UA-70830801-12', 'auto']
repo_url: https://github.com/getuliovinicius/configuracoes/
repo_name: GitHub
edit_uri: blob/master/mds/
remote_branch: gh-pages
remote_name: origin
docs_dir: 'mds'
pages:
    - Configurações: index.md
    - Sistemas Operacionais:
        - Arch Linux: 'sistemas-operacionais/arch-linux.md'
        - Debian9: 'sistemas-operacionais/debian9.md'
    - Git:
        - Git: 'git/git.md'
    - Shell:
        - zsh: 'shell/zsh.md'
    - Python:
        - virtualenv: 'python/virtualenv.md'
        - Mkdocs: 'python/mkdocs.md'
    - PHP:
        - PHP - com Apache: 'php/php-apache.md'
        - Phpmyadmin: 'php/phpmyadmin.md'
        - Hesk: 'php/hesk.md'
    - Java:
        - JRE: 'java/jre.md'
    - Node.JS:
        - Node.JS: 'nodejs/nodejs.md'
    - Servidores Web:
        - Apache2: 'servidores-web/apache.md'
        - Nginx: 'servidores-web/nginx.md'
    - Banco de Dados:
        - MySQL: 'banco-de-dados/mysql.md'
        - MongoDB: 'banco-de-dados/mongodb.md'
    - Editores:
        - Atom: 'editores-de-codigo/atom.md'
        - Brackets: 'editores-de-codigo/brackets.md'
        - Sublime Text: 'editores-de-codigo/sublime-text.md'
        - VS Code: 'editores-de-codigo/vs-code.md'
theme: readthedocs
extra:
    version: 1.0
markdown_extensions:
    - smarty
    - nl2br
    - admonition
    - codehilite
    - sane_lists
    - toc:
        permalink: True
        separator: "_"
    - footnotes
